<?php

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return null[][][]
 */
function all_movies_listing_theme($existing, $type, $theme, $path){

  return [
    'all-movies-listing' => [
      'variables' => [
        'pageTitle' => NULL,
        'movies' => NULL,
      ]
    ],
    'movie-reservation' => [
      'variables' => [
        'pageTitle' => NULL,
        'movie_categories' => NULL,
        'movies' => NULL,
      ]
    ]
  ];

}

/**
 * Connects CSS and JS libraries from this modile with templates.
 *
 * @param array $page
 */
function all_movies_listing_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'all_movies_listing/movie-reservation';
}

